"""initial

Revision ID: 065c49a94e0e
Revises: 
Create Date: 2026-04-02 12:31:48.741823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '065c49a94e0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_constraint(op.f('teams_name_key'), 'teams', type_='unique')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_unique_constraint(op.f('teams_name_key'), 'teams', ['name'], postgresql_nulls_not_distinct=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('business', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('phone_no', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###
